### ISSUE TITLE
How does this handle UTF-8 input?

### ISSUE THREAD

**Issue by warmwaffles** [justinmeiners/lisp-interpreter#17]
I'm currently evaluating what I want to use for a scripting language in some game ideas that I have and am curious if this will work well.

**Comment by justinmeiners** [comment]
No UTF8, just ASCII. Although, I would certainly be open to it, since the string type is self contained. UTF16 might be a better fit. In any case, to do it right, I think I one would really have to dig into the scheme spec.

One feature which  is missing, and can be important for games is the ability to sleep execution and resume. If you need that, I would recommend lua.

**Comment by warmwaffles** [comment]
You could also take a look into a pre-existing solution that works well (in my personal experiences) https://github.com/sheredom/utf8.h

**Comment by justinmeiners** [comment]
@warmwaffles Great! Thanks for the recommendation. Look's right up my alley.

**Comment by warmwaffles** [comment]
👍🏻
